//! Coder compatibility contract verification harness (WP-00).
//!
//! This is an executable, reproducible check that the current Openflows code
//! integrates with the pinned Coder deployment the way the centralized
//! deployment specifications require. It follows the repository convention of
//! `#[ignore]`d live integration tests (see `openflows-harness/tests/`).
//!
//! # Test groups (selected by the wrapper, never all at once)
//!
//! Tests are named with a stable prefix so the wrapper can select exactly one
//! group and **never** run destructive cleanup during a normal verification:
//!
//! - `ro_*` — read-only checks (no Coder mutation).
//! - `mut_*` — opt-in mutating scenario that creates the isolation fixtures.
//! - `iso_*` — cross-tenant isolation check against the fixtures from `mut_`.
//! - `cleanup_*` — deletes only resources recorded in the ledger; run explicitly.
//!
//! Non-`#[ignore]`d `#[test]` functions in the `offline` module are pure,
//! dependency-free regression tests for the parsing/validation helpers below;
//! they run with a plain `cargo test` and never touch a deployment.
//!
//! # Wrapper modes (`tests/integration/coder_compatibility.sh`)
//!
//! ```sh
//! # Read-only (no mutation):
//! export CODER_URL=... CODER_SESSION_TOKEN=...
//! ./tests/integration/coder_compatibility.sh
//!
//! # Mutating scenario (creates the two isolation orgs + workspace fixtures):
//! export OPENFLOWS_CODER_MUTATE=1
//! export OPENFLOWS_CODER_TEST_ORG_PREFIX=ofci-$(whoami)-
//! ./tests/integration/coder_compatibility.sh --mutating
//!
//! # Isolation check (must run after --mutating populated the fixtures):
//! ./tests/integration/coder_compatibility.sh --isolation
//!
//! # Cleanup (only resources recorded in the ledger):
//! ./tests/integration/coder_compatibility.sh --cleanup
//! ```
//!
//! # Safety
//!
//! - Mutating resources are created only inside the opt-in isolated test
//!   organization prefix, under a single ordered scenario. No check targets
//!   the default organization.
//! - Every created resource is recorded **immediately** in a persistent,
//!   atomically-written ledger keyed by `(deployment, org, kind, resource id)`.
//!   Cleanup validates the deployment URL and org before deleting, deletes
//!   children before parents, org-scopes every delete, and **retains** entries
//!   whose deletion failed (it never deletes the ledger blindly).
//! - Credentials are never printed. The one-time provisioner daemon secret and
//!   machine-identity tokens are written to 0600 temp files and consumed
//!   programmatically; session tokens are never echoed.
//! - Missing environment is a reported `NOT_VERIFIED`; mandatory isolation
//!   fixtures that are absent are a hard failure, never fabricated evidence.

use coder_client::CoderClient;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::process::Command;
use std::sync::Mutex;

/// Baseline Coder version this repository targets (docker-compose.yml default).
const EXPECTED_CODER_VERSION: &str = "v2.37.3";

/// Length of the raw provisioner key secret generated by Coder
/// (`provisionerkey.New` -> `apikey.GenerateSecret(43)` -> `cryptorand.String(43)`
/// using the default `0-9A-Za-z` charset).
const PROVISIONER_KEY_SECRET_LEN: usize = 43;

/// Env vars.
const ENV_CODER_URL: &str = "CODER_URL";
const ENV_CODER_TOKEN: &str = "CODER_SESSION_TOKEN";
const ENV_CODER_TOKEN_FILE: &str = "CODER_SESSION_TOKEN_FILE";
const ENV_MUTATE: &str = "OPENFLOWS_CODER_MUTATE";
const ENV_ORG_PREFIX: &str = "OPENFLOWS_CODER_TEST_ORG_PREFIX";
const ENV_LEDGER_FILE: &str = "OPENFLOWS_CODER_LEDGER_FILE";
/// Explicit org names + workspace fixture names for the isolation check
/// (created by the mutating scenario and exported by the wrapper).
const ENV_ORG_A: &str = "OPENFLOWS_CODER_ORG_A";
const ENV_ORG_B: &str = "OPENFLOWS_CODER_ORG_B";
const ENV_WS_A: &str = "OPENFLOWS_CODER_WS_A";
const ENV_WS_B: &str = "OPENFLOWS_CODER_WS_B";
const ENV_TOKEN_A_FILE: &str = "OPENFLOWS_CODER_TOKEN_A_FILE";
const ENV_TOKEN_B_FILE: &str = "OPENFLOWS_CODER_TOKEN_B_FILE";

/// Regex fragments for token-like strings that must never reach logs.
fn token_patterns() -> &'static [&'static str] {
    &[
        r"(?i)bearer\s+[A-Za-z0-9._~+/=-]{8,}",
        r"(?i)(coder|ghp|gho|ghs|github_pat|glpat)[_-][A-Za-z0-9_]{16,}",
        r"(?i)(token|secret|password|apikey|access_key)\s*[=:]\s*[A-Za-z0-9._~+/=-]{8,}",
        r"[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}",
        r"(?i)CODER_SESSION_TOKEN\s*[=:]\s*\S+",
    ]
}

/// Scrub token-like patterns from arbitrary text (JSON or plaintext).
fn redact_string(s: &str) -> String {
    let mut out = s.to_string();
    for pat in token_patterns() {
        if let Ok(re) = regex::Regex::new(pat) {
            out = re.replace_all(&out, "<REDACTED>").to_string();
        }
    }
    out
}

/// Recursively redact a serde value by field name, for structured bodies.
fn redact(v: &Value) -> Value {
    match v {
        Value::Object(map) => {
            let mut out = serde_json::Map::new();
            for (k, val) in map {
                let key_lc = k.to_ascii_lowercase();
                if key_lc.contains("token")
                    || key_lc.contains("secret")
                    || key_lc.contains("password")
                    || key_lc.contains("key")
                    || key_lc.contains("access_token")
                {
                    out.insert(k.clone(), Value::String("<REDACTED>".into()));
                } else {
                    out.insert(k.clone(), redact(val));
                }
            }
            Value::Object(out)
        }
        Value::Array(arr) => Value::Array(arr.iter().map(redact).collect()),
        other => other.clone(),
    }
}

/// Resolve the operator session token without ever echoing it.
fn resolve_token() -> Option<String> {
    if let Ok(t) = std::env::var(ENV_CODER_TOKEN) {
        if !t.trim().is_empty() {
            return Some(t);
        }
    }
    if let Ok(path) = std::env::var(ENV_CODER_TOKEN_FILE) {
        if let Ok(t) = std::fs::read_to_string(&path) {
            let t = t.trim().to_string();
            if !t.is_empty() {
                return Some(t);
            }
        }
    }
    None
}

fn coder_url() -> Option<String> {
    let url = std::env::var(ENV_CODER_URL).ok()?;
    if url.trim().is_empty() {
        None
    } else {
        Some(url.trim_end_matches('/').to_string())
    }
}

/// An HTTP client with a per-request timeout so one hung request cannot exceed
/// an enclosing polling deadline.
fn http_client() -> reqwest::Client {
    reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(15))
        .build()
        .unwrap_or_default()
}

/// Fail with a `NOT_VERIFIED` marker when the live environment is absent.
fn require_live_client() -> CoderClient {
    let url = coder_url().expect(
        "NOT_VERIFIED: CODER_URL is not set; no licensed Coder deployment was configured. \
         This check cannot run and is reported NOT_VERIFIED, not VERIFIED_LIVE.",
    );
    let token = resolve_token().expect(
        "NOT_VERIFIED: neither CODER_SESSION_TOKEN nor CODER_SESSION_TOKEN_FILE is set. \
         This check cannot run and is reported NOT_VERIFIED, not VERIFIED_LIVE.",
    );
    CoderClient::new(&url, &token)
}

fn mutate_enabled() -> bool {
    std::env::var(ENV_MUTATE).map(|v| v == "1").unwrap_or(false)
}

fn require_mutate() {
    assert!(
        mutate_enabled(),
        "NOT_VERIFIED: mutating checks require OPENFLOWS_CODER_MUTATE=1. \
         Refusing to create resources without explicit opt-in."
    );
}

fn org_prefix() -> String {
    std::env::var(ENV_ORG_PREFIX).unwrap_or_else(|_| "ofci-".to_string())
}

fn run_suffix() -> String {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    format!("{:x}", nanos % 0xFFFF_FFFF)
}

fn assert_not_default_org(org: &str) {
    assert!(
        !org.eq_ignore_ascii_case("coder") && !org.is_empty(),
        "Refusing to mutate the default organization (org={org}). \
         Mutating checks must target the isolated test org prefix."
    );
}

/// Run a `coder` CLI subcommand synchronously. Never passes the token on argv.
/// `org` scopes the command via CODER_ORGANIZATION when non-empty.
fn coder_cli(args: &[&str], org: &str) -> Result<String, String> {
    let url = coder_url().ok_or("CODER_URL not set")?;
    let token = resolve_token().ok_or("session token not set")?;
    let mut cmd = Command::new("coder");
    cmd.args(args)
        .env("CODER_URL", &url)
        .env("CODER_SESSION_TOKEN", &token)
        .env("CODER_TOKEN", &token);
    if !org.is_empty() {
        cmd.env("CODER_ORGANIZATION", org);
    }
    let out = cmd
        .output()
        .map_err(|e| format!("failed to spawn `coder`: {e}"))?;
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
    if !out.status.success() {
        return Err(format!(
            "`coder {}` exited {}: stderr={}",
            args.join(" "),
            out.status,
            redact_string(&stderr)
        ));
    }
    Ok(stdout)
}

/// Run a `coder` CLI subcommand under a wall-clock timeout (async).
///
/// `kill_on_drop(true)` is required so that when the enclosing `timeout`
/// future is dropped the child process is killed and reaped instead of being
/// orphaned and left creating resources after the scenario has moved on.
async fn coder_cli_timeout(
    args: &[&str],
    org: &str,
    timeout: std::time::Duration,
) -> Result<String, String> {
    let url = coder_url().ok_or("CODER_URL not set")?;
    let token = resolve_token().ok_or("session token not set")?;
    let mut cmd = tokio::process::Command::new("coder");
    cmd.args(args)
        .env("CODER_URL", &url)
        .env("CODER_SESSION_TOKEN", &token)
        .env("CODER_TOKEN", &token)
        .kill_on_drop(true);
    if !org.is_empty() {
        cmd.env("CODER_ORGANIZATION", org);
    }
    let out = tokio::time::timeout(timeout, cmd.output())
        .await
        .map_err(|_| format!("`coder {}` timed out after {timeout:?}", args.join(" ")))?
        .map_err(|e| format!("failed to spawn `coder`: {e}"))?;
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
    if !out.status.success() {
        return Err(format!(
            "`coder {}` exited {}: stderr={}",
            args.join(" "),
            out.status,
            redact_string(&stderr)
        ));
    }
    Ok(stdout)
}

// ── Persistent, atomically-written resource ledger ─────────────────────────
// Every entry records the deployment URL, organization, and the resource's
// immutable ID so cleanup can validate that a recorded resource belongs to
// THIS deployment and org before deleting it, and so distinct resources with
// the same human name in different orgs never collide. Identity is
// `(deployment_url, org, kind, resource_id)`. The read-modify-write cycle is
// serialized with a cross-process lock file so two harness processes cannot
// clobber one another's ledger. Entries are appended/updated under that lock
// and the file is rewritten atomically. Status transitions are `created` ->
// `delete_failed` | `deleted`; entries that fail to delete are retained.

#[derive(Serialize, Deserialize, Clone)]
struct LedgerEntry {
    deployment_url: String,
    org: String,
    kind: String, // org | template | provisioner_key | user | workspace
    /// Human-facing name/identifier (e.g. template name, `owner/ws`).
    id: String,
    /// Immutable server-assigned resource ID (template_id, workspace_id, ...).
    /// Empty only when the ID could not be resolved before recording.
    resource_id: String,
    status: String, // created | deleted | delete_failed
}

#[derive(Serialize, Deserialize, Default)]
struct Ledger {
    entries: Vec<LedgerEntry>,
}

static LEDGER_LOCK: Mutex<()> = Mutex::new(());

fn ledger_path() -> std::path::PathBuf {
    if let Ok(p) = std::env::var(ENV_LEDGER_FILE) {
        return std::path::PathBuf::from(p);
    }
    std::env::temp_dir().join("ofci-ledger.json")
}

fn load_ledger_locked() -> Ledger {
    let path = ledger_path();
    if let Ok(text) = std::fs::read_to_string(&path) {
        if let Ok(ledger) = serde_json::from_str::<Ledger>(&text) {
            return ledger;
        }
    }
    Ledger::default()
}

fn persist_ledger(ledger: &Ledger) {
    let path = ledger_path();
    let text = serde_json::to_string_pretty(ledger).expect("serialize ledger");
    // Atomic write: write temp then rename so a crash never leaves a torn file.
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, text).expect("write ledger temp");
    std::fs::rename(&tmp, &path).expect("atomic ledger replace");
    println!("ledger written to {}", path.display());
}

/// Acquire a cross-process exclusive lock on the ledger and run `f`, releasing
/// the lock afterwards. Guards the read-modify-write cycle against a second
/// harness process; the in-process mutex handles threads in the same process.
fn with_ledger_lock<T>(f: impl FnOnce() -> T) -> T {
    let _guard = LEDGER_LOCK.lock().expect("ledger lock poisoned");
    let lock_path = ledger_path().with_extension("lock");
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(30);
    let lock_file = loop {
        match std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&lock_path)
        {
            Ok(f) => break f,
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
                if std::time::Instant::now() >= deadline {
                    panic!("timed out acquiring ledger lock {}", lock_path.display());
                }
                std::thread::sleep(std::time::Duration::from_millis(100));
            }
            Err(e) => panic!("failed to create ledger lock {}: {e}", lock_path.display()),
        }
    };
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(f));
    drop(lock_file);
    let _ = std::fs::remove_file(&lock_path);
    match result {
        Ok(v) => v,
        Err(p) => std::panic::resume_unwind(p),
    }
}

/// The composite identity key for a ledger entry.
fn ledger_identity(deployment: &str, org: &str, kind: &str, resource_id: &str) -> String {
    format!("{deployment}\u{1f}::{org}\u{1f}::{kind}\u{1f}::{resource_id}")
}

/// Record a created resource immediately. `org` is the org it belongs to;
/// `resource_id` is the immutable server-assigned ID when known (empty
/// otherwise). Panics on write failure so a lost record (and thus an unsafe
/// cleanup) is never silent.
///
/// Identity is `(deployment, org, kind, resource_id)`. When a resource is
/// recorded with an empty `resource_id` (its server ID not yet resolved, e.g. a
/// workspace recorded immediately after creation) and later re-recorded with
/// the real ID, the same entry is updated rather than duplicated: matching
/// falls back to the human `id` while either side has an empty `resource_id`.
fn ledger_record(deployment_url: &str, org: &str, kind: &str, id: &str, resource_id: &str) {
    with_ledger_lock(|| {
        let mut ledger = load_ledger_locked();
        let key = ledger_identity(deployment_url, org, kind, resource_id);
        let existing = ledger.entries.iter_mut().find(|e| {
            let by_resource =
                ledger_identity(&e.deployment_url, &e.org, &e.kind, &e.resource_id) == key;
            let by_human_id = (resource_id.is_empty() || e.resource_id.is_empty())
                && e.deployment_url == deployment_url
                && e.org == org
                && e.kind == kind
                && e.id == id;
            by_resource || by_human_id
        });
        if let Some(e) = existing {
            e.status = "created".to_string();
            e.deployment_url = deployment_url.to_string();
            e.org = org.to_string();
            e.id = id.to_string();
            if !resource_id.is_empty() {
                e.resource_id = resource_id.to_string();
            }
        } else {
            ledger.entries.push(LedgerEntry {
                deployment_url: deployment_url.to_string(),
                org: org.to_string(),
                kind: kind.to_string(),
                id: id.to_string(),
                resource_id: resource_id.to_string(),
                status: "created".to_string(),
            });
        }
        persist_ledger(&ledger);
    });
}

/// Mark a ledger entry's deletion outcome and retain it unless fully deleted.
fn ledger_delete_result(kind: &str, id: &str, resource_id: &str, org: &str, ok: bool) {
    with_ledger_lock(|| {
        let mut ledger = load_ledger_locked();
        for e in ledger.entries.iter_mut() {
            let id_matches = if resource_id.is_empty() {
                e.id == id
            } else {
                e.resource_id == resource_id
            };
            if e.kind == kind && e.org == org && id_matches {
                e.status = if ok { "deleted" } else { "delete_failed" }.to_string();
            }
        }
        // Retain entries that failed; drop only fully-deleted ones.
        ledger.entries.retain(|e| e.status != "deleted");
        persist_ledger(&ledger);
    });
}

// ── Provisioner key parsing ────────────────────────────────────────────────
//
// The pinned Coder (`v2.37.3`) generates a raw 43-character alphanumeric
// secret (`provisionerkey.New` -> `apikey.GenerateSecret(43)` ->
// `cryptorand.String(43)` using the default `0-9A-Za-z` charset). It does NOT
// carry a `coder_` prefix. `coder provisioner keys create` is not even exposed
// by the AGPL CLI; the structured API response is the canonical source:
// `POST /api/v2/organizations/{org}/provisionerkeys` -> `{"key": "<secret>"}`.
//
// The parser accepts either that structured JSON `key` field or a standalone
// 43-character line (as a real CLI would print it), and validates the shape.

/// True when `s` is a well-formed raw provisioner secret: exactly 43 chars,
/// all in `0-9A-Za-z`.
fn is_provisioner_secret(s: &str) -> bool {
    if s.len() != PROVISIONER_KEY_SECRET_LEN {
        return false;
    }
    s.chars().all(|c| c.is_ascii_alphanumeric())
}

/// Extract the one-time provisioner daemon secret from command output or a
/// structured API response, without ever logging it. Never echoes the token.
fn extract_daemon_key(key_out: &str) -> Option<String> {
    // Structured API response: `{"key": "<43-char secret>"}`.
    if let Ok(v) = serde_json::from_str::<Value>(key_out) {
        if let Some(k) = v.get("key").and_then(Value::as_str) {
            if is_provisioner_secret(k) {
                return Some(k.to_string());
            }
        }
    }
    // Plaintext: a standalone line that is exactly the raw 43-char secret.
    let re = regex::Regex::new(r"(?m)^([A-Za-z0-9]{43})\s*$").ok()?;
    for cap in re.captures_iter(key_out) {
        if let Some(m) = cap.get(1) {
            let cand = m.as_str();
            if is_provisioner_secret(cand) {
                return Some(cand.to_string());
            }
        }
    }
    None
}

/// Create a provisioner key via the structured REST API (the canonical,
/// version-agnostic route) and return the raw daemon secret.
async fn create_provisioner_key_api(
    client: &CoderClient,
    org_id: &str,
    name: &str,
) -> Result<String, String> {
    let resp = http_client()
        .post(format!(
            "{}/api/v2/organizations/{}/provisionerkeys",
            client.base_url(),
            org_id
        ))
        .header("Authorization", format!("Bearer {}", client.token()))
        .json(&serde_json::json!({ "name": name }))
        .send()
        .await
        .map_err(|e| format!("provisioner key create request failed: {e}"))?;
    let status = resp.status().as_u16();
    let body: Value = resp.json().await.unwrap_or(Value::Null);
    if status != 201 {
        return Err(format!(
            "provisioner key create returned {status}: {}",
            redact(&body)
        ));
    }
    let key = body
        .get("key")
        .and_then(Value::as_str)
        .ok_or_else(|| format!("provisioner key response missing `key`: {}", redact(&body)))?;
    if !is_provisioner_secret(key) {
        return Err(format!(
            "provisioner key response `key` is not a valid {PROVISIONER_KEY_SECRET_LEN}-char secret"
        ));
    }
    Ok(key.to_string())
}

/// Delete a provisioner key via REST (the AGPL CLI exposes no delete command).
async fn delete_provisioner_key_api(
    client: &CoderClient,
    org_id: &str,
    name: &str,
) -> Result<(), String> {
    let resp = http_client()
        .delete(format!(
            "{}/api/v2/organizations/{}/provisionerkeys/{}",
            client.base_url(),
            org_id,
            name
        ))
        .header("Authorization", format!("Bearer {}", client.token()))
        .send()
        .await
        .map_err(|e| format!("provisioner key delete request failed: {e}"))?;
    if resp.status().as_u16() == 204 || resp.status().is_success() {
        Ok(())
    } else {
        Err(format!("provisioner key delete returned {}", resp.status()))
    }
}

// ── Provisioner daemon readiness ───────────────────────────────────────────
//
// The pinned server registers the daemon listing at
// `/api/v2/organizations/{id}/provisionerdaemons` (NOT `/provisioners`), and a
// nonempty response alone does not establish that the intended daemon is
// connected. We verify identity (`key_name` matches the key we created) and
// usability (`status` is `idle` or `busy`, never `offline`).

/// Returns `(ready, reason)`. `ready` is true only when a provisioner daemon
/// authenticated with `key_name` reports an online status.
async fn provisioner_daemons_ready(
    client: &CoderClient,
    org_id: &str,
    key_name: &str,
) -> (bool, String) {
    let resp = http_client()
        .get(format!(
            "{}/api/v2/organizations/{}/provisionerdaemons",
            client.base_url(),
            org_id
        ))
        .header("Authorization", format!("Bearer {}", client.token()))
        .send()
        .await;
    let body: Value = match resp {
        Ok(r) if r.status().is_success() => r.json().await.unwrap_or(Value::Null),
        Ok(r) => return (false, format!("provisionerdaemons HTTP {}", r.status())),
        Err(e) => return (false, format!("provisionerdaemons request failed: {e}")),
    };
    let daemons = body.as_array().cloned().unwrap_or_default();
    if daemons.is_empty() {
        return (false, "no provisioner daemons reported".to_string());
    }
    for d in &daemons {
        let key_name_field = d.get("key_name").and_then(Value::as_str).unwrap_or("");
        if key_name_field == key_name {
            let status = d.get("status").and_then(Value::as_str).unwrap_or("unknown");
            let daemon_name = d.get("name").and_then(Value::as_str).unwrap_or("<unnamed>");
            match status {
                "idle" | "busy" => return (true, format!("daemon {daemon_name} is {status}")),
                _ => {
                    return (
                        false,
                        format!("daemon {daemon_name} for key {key_name} is {status}"),
                    )
                }
            }
        }
    }
    (
        false,
        format!("no daemon for key {key_name} found in the listing"),
    )
}

async fn wait_for_provisioner_ready(
    client: &CoderClient,
    org_id: &str,
    key_name: &str,
    timeout: std::time::Duration,
) {
    let deadline = std::time::Instant::now() + timeout;
    loop {
        let (ready, reason) = provisioner_daemons_ready(client, org_id, key_name).await;
        if ready {
            println!("VERIFIED_LIVE provisioner ready for org {org_id}: {reason}");
            return;
        }
        if std::time::Instant::now() >= deadline {
            panic!(
                "provisioner for org {org_id} not ready within {timeout:?} ({reason}); \
                 template import cannot be exercised"
            );
        }
        tokio::time::sleep(std::time::Duration::from_secs(2)).await;
    }
}

/// Path to the 0600 file holding a provisioner daemon's one-time secret for an
/// org, so cleanup can spin the daemon back up to run Terraform deletion jobs.
fn provisioner_secret_path(org_id: &str) -> std::path::PathBuf {
    std::env::temp_dir().join(format!("ofci-daemon-key-{org_id}.secret"))
}

fn write_provisioner_secret(org_id: &str, secret: &str) -> std::path::PathBuf {
    use std::os::unix::fs::PermissionsExt;
    let path = provisioner_secret_path(org_id);
    std::fs::write(&path, secret).expect("write provisioner daemon secret file");
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))
        .expect("chmod 0600 provisioner daemon secret");
    path
}

fn read_provisioner_secret(org_id: &str) -> Option<String> {
    std::fs::read_to_string(provisioner_secret_path(org_id))
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
}

fn start_provisioner_daemon(org_id: &str) -> tokio::process::Child {
    let url = coder_url().expect("CODER_URL");
    let secret = read_provisioner_secret(org_id)
        .unwrap_or_else(|| panic!("no stored provisioner daemon secret for org {org_id}"));
    let mut cmd = tokio::process::Command::new("coder");
    cmd.args(["provisionerd", "start", "--org", org_id])
        .env("CODER_URL", &url)
        .env("CODER_PROVISIONER_DAEMON_KEY", &secret)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .kill_on_drop(true);
    cmd.spawn().expect("spawn provisionerd")
}

async fn stop_provisioner_daemon(daemon: &mut tokio::process::Child) {
    let _ = daemon.kill().await;
    let _ = daemon.wait().await;
}

// ── Workspace lookup + verification ────────────────────────────────────────
//
// The workspace list endpoint filters by the caller's visibility and uses the
// `q` search parameter, so we resolve a workspace by exact name, then assert
// the exact identity fields (organization, owner, template, build version).

/// Find a workspace object in a `WorkspacesResponse` body by exact name.
/// Returns `None` when absent (empty 200 is a valid, correct outcome).
fn find_workspace_in_response(body: &Value, name: &str) -> Option<Value> {
    body.get("workspaces")
        .and_then(Value::as_array)
        .and_then(|arr| {
            arr.iter()
                .find(|w| w.get("name").and_then(Value::as_str) == Some(name))
                .cloned()
        })
}

/// Validate that a workspace JSON object carries the exact expected identity.
/// Returns `Ok(workspace_id)` when every field matches, otherwise `Err` naming
/// the first mismatched field.
///
/// Build semantics follow the pinned API: `latest_build.status` is a
/// `WorkspaceStatus` (a successful *start* reports `running`, never
/// `succeeded`), while `latest_build.job.status` is a `ProvisionerJobStatus`
/// that reports `succeeded` when the provisioning job finishes. Both must hold.
fn validate_workspace_identity(
    ws: &Value,
    expected_org_id: &str,
    expected_owner: &str,
    expected_template: &str,
    expected_version: &str,
    expected_workspace_status: &str,
) -> Result<String, String> {
    let id = ws
        .get("id")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();
    let org = ws
        .get("organization_id")
        .and_then(Value::as_str)
        .unwrap_or("");
    if org != expected_org_id {
        return Err(format!(
            "organization mismatch: got {org}, expected {expected_org_id}"
        ));
    }
    let owner = ws.get("owner_name").and_then(Value::as_str).unwrap_or("");
    if owner != expected_owner {
        return Err(format!(
            "owner mismatch: got {owner}, expected {expected_owner}"
        ));
    }
    let template = ws
        .get("template_name")
        .and_then(Value::as_str)
        .unwrap_or("");
    if template != expected_template {
        return Err(format!(
            "template mismatch: got {template}, expected {expected_template}"
        ));
    }
    let build = ws.get("latest_build").and_then(Value::as_object);
    let version = build
        .and_then(|b| b.get("template_version_name"))
        .and_then(Value::as_str)
        .unwrap_or("");
    if version != expected_version {
        return Err(format!(
            "template version mismatch: got {version}, expected {expected_version}"
        ));
    }
    // `latest_build.status` is a WorkspaceStatus: a successful start is
    // `running`, never `succeeded`.
    let workspace_status = build
        .and_then(|b| b.get("status"))
        .and_then(Value::as_str)
        .unwrap_or("");
    if workspace_status != expected_workspace_status {
        return Err(format!(
            "workspace status mismatch: got {workspace_status}, expected {expected_workspace_status}"
        ));
    }
    // `latest_build.job.status` is the ProvisionerJobStatus; `succeeded` means
    // the provisioning job (the workspace build) completed.
    let job_status = build
        .and_then(|b| b.get("job"))
        .and_then(|j| j.get("status"))
        .and_then(Value::as_str)
        .unwrap_or("");
    if job_status != "succeeded" {
        return Err(format!(
            "provisioner job status mismatch: got {job_status}, expected succeeded"
        ));
    }
    Ok(id)
}

async fn fetch_workspace_by_name(client: &CoderClient, ws_name: &str) -> Result<Value, String> {
    let resp = http_client()
        .get(format!(
            "{}/api/v2/workspaces?q=name:{}",
            client.base_url(),
            ws_name
        ))
        .header("Authorization", format!("Bearer {}", client.token()))
        .send()
        .await
        .map_err(|e| format!("list workspaces request failed: {e}"))?;
    if !resp.status().is_success() {
        return Err(format!("list workspaces returned {}", resp.status()));
    }
    resp.json::<Value>()
        .await
        .map_err(|e| format!("list workspaces body invalid: {e}"))
}

/// Resolve the workspace by name and validate its exact identity. Returns the
/// workspace ID on success.
async fn verify_workspace_ownership(
    client: &CoderClient,
    ws_name: &str,
    org_id: &str,
    owner: &str,
    template: &str,
    version: &str,
) -> String {
    let body = fetch_workspace_by_name(client, ws_name)
        .await
        .unwrap_or_else(|e| panic!("verify workspace {ws_name}: {e}"));
    let ws = find_workspace_in_response(&body, ws_name)
        .unwrap_or_else(|| panic!("workspace {ws_name} not found in list response"));
    validate_workspace_identity(&ws, org_id, owner, template, version, "running")
        .unwrap_or_else(|e| panic!("workspace {ws_name} identity invalid: {e}"))
}

/// Wait for a workspace's latest build's provisioning job to reach a terminal
/// `succeeded` state, or fail. This is required because the scenario creates
/// workspaces with `--no-wait`; workspace lifecycle work (and the later
/// Terraform deletion job) needs a provisioner to complete.
///
/// Semantics follow the pinned API: `latest_build.job.status`
/// (`ProvisionerJobStatus`) is `succeeded` when the provisioning job finishes;
/// `latest_build.status` (`WorkspaceStatus`) reports `running` for a successful
/// start and never `succeeded`. We accept either the job reaching `succeeded`
/// or the workspace reaching `running`.
async fn wait_for_workspace_build_succeeded(
    client: &CoderClient,
    ws_name: &str,
    timeout: std::time::Duration,
) -> String {
    let deadline = std::time::Instant::now() + timeout;
    loop {
        let body = match fetch_workspace_by_name(client, ws_name).await {
            Ok(b) => b,
            Err(_) => {
                if std::time::Instant::now() >= deadline {
                    panic!("workspace {ws_name}: list failed before build succeeded within {timeout:?}");
                }
                tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                continue;
            }
        };
        if let Some(ws) = find_workspace_in_response(&body, ws_name) {
            let id = ws
                .get("id")
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string();
            let ws_status = ws
                .get("latest_build")
                .and_then(|b| b.get("status"))
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string();
            let job_status = ws
                .get("latest_build")
                .and_then(|b| b.get("job"))
                .and_then(|j| j.get("status"))
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string();
            // A successful start: job succeeded, and/or the workspace is running.
            if job_status == "succeeded" || ws_status == "running" {
                return id;
            }
            // Terminal failures.
            if matches!(
                ws_status.as_str(),
                "failed" | "canceled" | "canceling" | "deleted"
            ) || matches!(job_status.as_str(), "failed" | "canceled" | "canceling")
            {
                panic!("workspace {ws_name} build ended (status={ws_status}, job={job_status})");
            }
        }
        if std::time::Instant::now() >= deadline {
            panic!("workspace {ws_name} build did not succeed within {timeout:?}");
        }
        tokio::time::sleep(std::time::Duration::from_secs(3)).await;
    }
}

// ── Read-only checks (prefix `ro_`) ────────────────────────────────────────

#[tokio::test]
#[ignore = "requires a licensed Coder deployment in CODER_URL + CODER_SESSION_TOKEN"]
async fn ro_buildinfo_matches_pinned_version() {
    let client = require_live_client();
    let resp = reqwest::Client::new()
        .get(format!("{}/api/v2/buildinfo", client.base_url()))
        .send()
        .await
        .expect("GET /api/v2/buildinfo failed");
    assert_eq!(resp.status(), 200, "buildinfo status");
    let body: Value = resp.json().await.expect("buildinfo JSON");
    let version = body
        .get("version")
        .and_then(Value::as_str)
        .unwrap_or("<none>")
        .to_string();
    println!("buildinfo.version = {version}");
    if version == EXPECTED_CODER_VERSION {
        println!("VERIFIED_LIVE baseline: server version matches pinned default {EXPECTED_CODER_VERSION}");
    } else {
        println!(
            "BASELINE_DRIFT: server is {version}, expected default {EXPECTED_CODER_VERSION}. \
             Reconcile before WP-05 (config/env.rs defaults to v2.37.1)."
        );
        assert!(
            version.starts_with("v2.37."),
            "server version {version} is not on the pinned v2.37 line"
        );
    }
    println!("buildinfo (redacted) = {}", redact(&body));
}

#[tokio::test]
#[ignore = "requires a licensed Coder deployment"]
async fn ro_record_cli_version() {
    require_live_client();
    match coder_cli(&["version"], "") {
        Ok(out) => {
            let first = out.lines().next().unwrap_or("<none>").to_string();
            println!("VERIFIED_LIVE coder CLI: {first}");
        }
        Err(e) => println!("NOT_VERIFIED coder CLI version: {}", redact_string(&e)),
    }
}

#[tokio::test]
#[ignore = "requires a licensed Coder deployment"]
async fn ro_list_organizations_and_default_resolution() {
    let client = require_live_client();
    let orgs = client
        .list_organizations()
        .await
        .expect("list_organizations");
    assert!(!orgs.is_empty(), "expected at least the default org");
    let default_id = client
        .get_default_organization_id()
        .await
        .expect("get_default_organization_id");
    println!(
        "VERIFIED_LIVE org_count={} default_org_id={}",
        orgs.len(),
        default_id
    );
    for o in &orgs {
        println!("org {} name={} is_default={}", o.id, o.name, o.is_default);
    }
}

#[tokio::test]
#[ignore = "requires a licensed Coder deployment"]
async fn ro_list_templates_in_default_org() {
    let client = require_live_client();
    let templates = client.list_templates().await.expect("list_templates");
    println!("VERIFIED_LIVE template_count={}", templates.len());
    for t in &templates {
        println!("template id={} name={}", t.id, t.name);
    }
}

#[cfg(feature = "chats-api")]
#[tokio::test]
#[ignore = "requires a licensed Coder deployment with Agents/chat license"]
async fn ro_list_chat_models_org_scoped() {
    let client = require_live_client();
    let models: Vec<coder_client::types::ModelInfo> = client
        .list_chat_models()
        .await
        .expect("list_chat_models (org-scoped)");
    println!("VERIFIED_LIVE model_count={}", models.len());
    for m in &models {
        println!("model id={} name={} provider={}", m.id, m.name, m.provider);
    }
}

#[tokio::test]
#[ignore = "requires a licensed Coder deployment"]
async fn ro_me_and_token_scope() {
    let client = require_live_client();
    let me = client.get_me().await.expect("get_me");
    println!(
        "VERIFIED_LIVE token authenticated as user id={} username={}",
        me.id, me.username
    );
}

/// Sanitized environment summary; never prints credentials.
#[test]
#[ignore = "environment summary"]
fn ro_env_summary() {
    println!(
        "CODER_URL={} token_set={} OPENFLOWS_CODER_MUTATE={} ORG_PREFIX={}",
        coder_url().unwrap_or_default(),
        resolve_token().is_some(),
        mutate_enabled(),
        org_prefix()
    );
}

// ── Mutating scenario (prefix `mut_`, single ordered test) ─────────────────
// One ordered scenario so every step's prerequisites exist before the next:
// org -> provisioner key (structured API) + running daemon -> machine identity
// + roles -> template version -> workspace (explicit org/owner/version) ->
// build waited to success -> token minted for the isolation identity. Every
// resource is recorded in the ledger immediately after it is created, keyed by
// its immutable resource ID. Two orgs (A and B) are provisioned so the
// isolation check has real cross-tenant fixtures.

struct OrgFixture {
    org_name: String,
    org_id: String,
    workspace_name: String,
    token_file: String,
}

async fn provision_org_fixture(
    client: &CoderClient,
    deployment: &str,
    suffix: &str,
    label: &str,
) -> OrgFixture {
    let cmd_timeout = std::time::Duration::from_secs(180);
    let org = format!("{}{}-{}", org_prefix(), label, suffix);
    assert_not_default_org(&org);

    // 1. Organization.
    let _ = coder_cli_timeout(&["organizations", "create", &org], "", cmd_timeout).await;
    let orgs = client
        .list_organizations()
        .await
        .expect("list_organizations");
    let org_id = orgs
        .iter()
        .find(|o| o.name == org)
        .map(|o| o.id.clone())
        .unwrap_or_else(|| panic!("org {org} not visible"));
    ledger_record(deployment, &org, "org", &org, &org_id);
    println!("VERIFIED_LIVE org {org} (id={org_id})");

    // 2. Org-scoped provisioner key via the structured API (the pinned server
    //    returns a raw 43-char secret in `{"key": ...}`; the AGPL CLI does not
    //    even expose `provisioner keys create`).
    let key_name = format!("ofci-key-{label}-{suffix}");
    let daemon_key = create_provisioner_key_api(client, &org_id, &key_name)
        .await
        .unwrap_or_else(|e| panic!("provisioner key create failed: {e}"));
    ledger_record(deployment, &org, "provisioner_key", &key_name, &key_name);
    // Persist the one-time daemon secret (0600) so cleanup can re-spawn the
    // daemon to run Terraform deletion jobs.
    write_provisioner_secret(&org_id, &daemon_key);
    let mut daemon = start_provisioner_daemon(&org_id);
    wait_for_provisioner_ready(
        client,
        &org_id,
        &key_name,
        std::time::Duration::from_secs(120),
    )
    .await;

    // 3. Machine identity (service account) in the org.
    let username = format!("ofci-sa-{label}-{suffix}");
    coder_cli_timeout(
        &[
            "users",
            "create",
            "--service-account",
            "--username",
            &username,
            "--org",
            &org,
            "--email",
            &format!("{username}@invalid.local"),
        ],
        "",
        cmd_timeout,
    )
    .await
    .unwrap_or_else(|e| panic!("service account create failed: {}", redact_string(&e)));
    // Resolve the immutable user id for the ledger.
    let users = client.list_users().await.unwrap_or_default();
    let user_id = users
        .iter()
        .find(|u| u.username == username)
        .map(|u| u.id.clone())
        .unwrap_or_default();
    ledger_record(deployment, &org, "user", &username, &user_id);
    println!("VERIFIED_LIVE machine identity created: {username}");

    // 4. Assign org roles directly (service accounts do not inherit
    //    `agents-access`). Org-scoped via CODER_ORGANIZATION.
    coder_cli_timeout(
        &[
            "organizations",
            "members",
            "edit-roles",
            &username,
            "organization-workspace-access",
            "agents-access",
        ],
        &org,
        cmd_timeout,
    )
    .await
    .unwrap_or_else(|e| panic!("org role assign failed: {}", redact_string(&e)));
    println!("VERIFIED_LIVE machine identity roles assigned (workspace-access, agents-access)");

    // 5. Publish a template version into the org with an explicit version name.
    let template_name = format!("{}{}-{}", org_prefix(), "nexus", label);
    let version = format!("ofci-wp00-{suffix}");
    let tmp = tempfile::tempdir().expect("tempdir");
    std::fs::write(tmp.path().join("main.tf"), VALID_MINIMAL_MAIN_TF)
        .expect("write minimal main.tf");
    coder_cli_timeout(
        &[
            "templates",
            "push",
            "--yes",
            "--org",
            &org,
            "--name",
            &version,
            "-d",
            tmp.path().to_str().unwrap(),
            &template_name,
        ],
        "",
        cmd_timeout,
    )
    .await
    .unwrap_or_else(|e| panic!("templates push failed: {}", redact_string(&e)));
    let template_id = client
        .list_templates()
        .await
        .unwrap_or_default()
        .into_iter()
        .find(|t| t.name == template_name)
        .map(|t| t.id)
        .unwrap_or_default();
    ledger_record(deployment, &org, "template", &template_name, &template_id);
    println!("VERIFIED_LIVE published template version {version} for {template_name} in {org}");

    // 6. Workspace with explicit org, owner, and pinned version (no-wait).
    let ws_name = format!("ofci-check-{label}-{suffix}");
    coder_cli_timeout(
        &[
            "create",
            "--yes",
            "--org",
            &org,
            "--template",
            &template_name,
            "--template-version",
            &version,
            "--no-wait",
            &format!("{username}/{ws_name}"),
        ],
        "",
        cmd_timeout,
    )
    .await
    .unwrap_or_else(|e| {
        panic!(
            "workspace create with explicit version failed: {}",
            redact_string(&e)
        )
    });
    // Record the workspace in the ledger IMMEDIATELY after creation, before
    // any polling or validation. A failed build or timeout still leaves the
    // workspace tracked so cleanup can delete it (and its dependency chain).
    // The immutable resource id is not yet resolved, so it is recorded empty
    // and filled in below once the build resolves it (ledger_record updates
    // the same entry).
    ledger_record(
        deployment,
        &org,
        "workspace",
        &format!("{username}/{ws_name}"),
        "",
    );

    // 7. Wait for the workspace build to complete (job succeeded and/or the
    //    workspace running; a provisioner is still running here, so creation is
    //    not left queued).
    let ws_id =
        wait_for_workspace_build_succeeded(client, &ws_name, std::time::Duration::from_secs(300))
            .await;

    // 8. Verify the workspace's exact org/owner/template/version identity.
    verify_workspace_ownership(
        client,
        &ws_name,
        &org_id,
        &username,
        &template_name,
        &version,
    )
    .await;
    println!("VERIFIED_LIVE workspace {username}/{ws_name} org={org} version={version} id={ws_id}");
    ledger_record(
        deployment,
        &org,
        "workspace",
        &format!("{username}/{ws_name}"),
        &ws_id,
    );

    // 9. Mint a session token for the machine identity so the isolation check
    //    can act as this org-local identity. Written to a 0600 file.
    let token_file = mint_identity_token(client, &user_id, &username).await;

    // The provisioner daemon's job (workspace creation) is complete; drop it
    // (kill_on_drop kills the child). Cleanup spawns its own daemons from the
    // stored secret when it needs to run deletion jobs.
    stop_provisioner_daemon(&mut daemon).await;

    OrgFixture {
        org_name: org,
        org_id,
        workspace_name: ws_name,
        token_file,
    }
}

/// Mint an API token for a machine identity via the admin client and write it
/// to a 0600 file, returning the file path. If minting fails, an empty path is
/// returned and the isolation check will fail loudly when the token is absent.
async fn mint_identity_token(client: &CoderClient, user_id: &str, username: &str) -> String {
    use std::os::unix::fs::PermissionsExt;
    if user_id.is_empty() {
        return String::new();
    }
    let name = format!("ofci-iso-{username}");
    let path = std::env::temp_dir().join(format!("ofci-token-{user_id}.secret"));
    match client.create_api_token(user_id, &name).await {
        Ok(api_key) if !api_key.key.is_empty() => {
            std::fs::write(&path, api_key.key).expect("write identity token file");
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))
                .expect("chmod 0600 identity token");
            path.to_string_lossy().to_string()
        }
        Ok(_) => {
            println!("WARN: identity token for {username} minted empty; isolation may fail");
            String::new()
        }
        Err(e) => {
            println!(
                "WARN: could not mint identity token for {username} ({}); isolation may fail",
                redact_string(&e.to_string())
            );
            String::new()
        }
    }
}

#[tokio::test]
#[ignore = "requires OPENFLOWS_CODER_MUTATE=1 and a licensed deployment"]
async fn mut_scenario_provision_tenant() {
    require_mutate();
    let client = require_live_client();
    let deployment = coder_url().expect("CODER_URL");
    let suffix = run_suffix();

    // Provision org A (primary tenant) and org B (second isolation tenant).
    // Both get a real workspace fixture owned by an org-local machine identity.
    let fixture_a = provision_org_fixture(&client, &deployment, &suffix, "a").await;
    let fixture_b = provision_org_fixture(&client, &deployment, &suffix, "b").await;

    // Persist the isolation fixture coordinates + token file paths so the
    // cross-tenant isolation check can consume them in a later invocation.
    persist_fixture_manifest(&fixture_a, &fixture_b);
    println!(
        "VERIFIED_LIVE provisioned isolation fixtures orgA={} orgB={}",
        fixture_a.org_id, fixture_b.org_id
    );
}

/// Path of the isolation fixture manifest written by the mutating scenario and
/// sourced by the wrapper before running the isolation check.
fn fixture_manifest_path() -> std::path::PathBuf {
    std::env::temp_dir().join("ofci-isolation-manifest.env")
}

/// Write the isolation fixture coordinates (org names, workspace names, token
/// file paths) as shell export lines so the wrapper can `source` it and pass
/// them to `iso_cross_tenant`.
fn persist_fixture_manifest(a: &OrgFixture, b: &OrgFixture) {
    use std::io::Write;
    let path = fixture_manifest_path();
    let mut f = std::fs::File::create(&path).expect("create isolation manifest");
    writeln!(f, "export {ENV_ORG_A}='{}'", a.org_name).expect("write manifest");
    writeln!(f, "export {ENV_ORG_B}='{}'", b.org_name).expect("write manifest");
    writeln!(f, "export {ENV_WS_A}='{}'", a.workspace_name).expect("write manifest");
    writeln!(f, "export {ENV_WS_B}='{}'", b.workspace_name).expect("write manifest");
    if a.token_file.is_empty() {
        writeln!(f, "unset {ENV_TOKEN_A_FILE} || true").expect("write manifest");
    } else {
        writeln!(f, "export {ENV_TOKEN_A_FILE}='{}'", a.token_file).expect("write manifest");
    }
    if b.token_file.is_empty() {
        writeln!(f, "unset {ENV_TOKEN_B_FILE} || true").expect("write manifest");
    } else {
        writeln!(f, "export {ENV_TOKEN_B_FILE}='{}'", b.token_file).expect("write manifest");
    }
    println!(
        "isolation fixture manifest written to {} (the wrapper sources this for --isolation)",
        path.display()
    );
}

// ── Isolation check (prefix `iso_`, requires fixtures from `mut_`) ─────────
// Proves cross-tenant isolation with explicit org IDs, known workspace
// fixtures, and authenticated denials only. Positive controls first: each
// identity proves it can read ITS OWN org's models and list ITS OWN workspace
// fixture, and create a chat in its own org. Then negative controls: each
// identity must be denied access to the other org's workspace by its exact
// name, and denied chat access in the other org. A 401 is NOT treated as proof
// of isolation (it could indicate a broken credential rather than a denied
// access). Missing mandatory fixtures is a hard failure, not a silent pass.

#[tokio::test]
#[ignore = "requires OPENFLOWS_CODER_MUTATE=1, a licensed deployment, and two machine identities"]
async fn iso_cross_tenant() {
    require_mutate();
    require_live_client();
    let url = coder_url().expect("CODER_URL");

    // Mandatory fixtures: two org names, two workspace fixture names, two token
    // files. If any are missing, the isolation contract cannot be verified, so
    // this is a hard failure (not a misleading green NOT_VERIFIED return).
    let (org_a, org_b) = match (std::env::var(ENV_ORG_A).ok(), std::env::var(ENV_ORG_B).ok()) {
        (Some(a), Some(b)) if !a.is_empty() && !b.is_empty() => (a, b),
        _ => panic!(
            "MANDATORY isolation fixtures missing: OPENFLOWS_CODER_ORG_A / \
             OPENFLOWS_CODER_ORG_B must name the orgs created by --mutating. \
             Run the mutating scenario first, then re-run with the manifest sourced."
        ),
    };
    let (ws_a, ws_b) = match (std::env::var(ENV_WS_A).ok(), std::env::var(ENV_WS_B).ok()) {
        (Some(a), Some(b)) if !a.is_empty() && !b.is_empty() => (a, b),
        _ => panic!(
            "MANDATORY isolation fixtures missing: OPENFLOWS_CODER_WS_A / \
             OPENFLOWS_CODER_WS_B must name the workspace fixtures created by --mutating."
        ),
    };
    let (ta, tb) = match (
        std::env::var(ENV_TOKEN_A_FILE).ok(),
        std::env::var(ENV_TOKEN_B_FILE).ok(),
    ) {
        (Some(a), Some(b)) => (
            std::fs::read_to_string(&a)
                .expect("token A file")
                .trim()
                .to_string(),
            std::fs::read_to_string(&b)
                .expect("token B file")
                .trim()
                .to_string(),
        ),
        _ => panic!(
            "MANDATORY isolation fixtures missing: OPENFLOWS_CODER_TOKEN_A_FILE / \
             OPENFLOWS_CODER_TOKEN_B_FILE must point to tokens for the org A and \
             org B machine identities."
        ),
    };
    let ca = CoderClient::new(&url, &ta);
    let cb = CoderClient::new(&url, &tb);

    // Resolve each org's ID with the token that owns it.
    let org_id_a = org_id_for(&ca, &org_a).await;
    let org_id_b = org_id_for(&cb, &org_b).await;

    // ── Positive controls ──────────────────────────────────────────────
    let models_a = read_models_expect(&ca, &org_id_a, "A reads own org A models").await;
    let models_b = read_models_expect(&cb, &org_id_b, "B reads own org B models").await;
    println!(
        "positive control: A read {} models in {org_a}, B read {} models in {org_b}",
        models_a, models_b
    );

    // Each identity lists and sees ITS OWN workspace fixture. A request failure
    // here is a hard error, never a pass.
    assert!(
        matches!(
            workspace_access(&ca, &ws_a)
                .await
                .unwrap_or_else(|e| panic!("positive control A on {ws_a}: {e}")),
            WorkspaceAccess::Visible
        ),
        "positive control failed: A cannot see its own workspace {ws_a}"
    );
    assert!(
        matches!(
            workspace_access(&cb, &ws_b)
                .await
                .unwrap_or_else(|e| panic!("positive control B on {ws_b}: {e}")),
            WorkspaceAccess::Visible
        ),
        "positive control failed: B cannot see its own workspace {ws_b}"
    );
    println!("positive control: A sees {ws_a}, B sees {ws_b}");

    assert!(
        chat_access_ok(&ca, &org_id_a).await,
        "positive control failed: A cannot create a chat in its own org"
    );
    assert!(
        chat_access_ok(&cb, &org_id_b).await,
        "positive control failed: B cannot create a chat in its own org"
    );
    println!("positive control: A and B can each create a chat in their own org");

    // ── Negative controls (authenticated denials / invisible resources) ─
    // Workspaces: A must not see B's fixture, and vice versa. Only a valid
    // outcome (empty 200 or explicit 403/404) establishes isolation; a request
    // failure or unexpected status fails the check instead of passing it.
    let a_ws_on_b = workspace_access(&ca, &ws_b)
        .await
        .unwrap_or_else(|e| panic!("A->B workspace check failed (unexpected): {e}"));
    assert!(
        matches!(a_ws_on_b, WorkspaceAccess::NotVisible),
        "VERIFIED_LIVE FAILURE: A can see B's workspace {ws_b} — cross-tenant leak"
    );
    let b_ws_on_a = workspace_access(&cb, &ws_a)
        .await
        .unwrap_or_else(|e| panic!("B->A workspace check failed (unexpected): {e}"));
    assert!(
        matches!(b_ws_on_a, WorkspaceAccess::NotVisible),
        "VERIFIED_LIVE FAILURE: B can see A's workspace {ws_a} — cross-tenant leak"
    );
    println!("negative control: cross-tenant workspace access denied in both directions");

    // Models: A must not read B's org models, and vice versa. A 401 or request
    // failure is NOT accepted as proof of isolation.
    let a_models_on_b = read_models_status(&ca, &org_id_b).await;
    let b_models_on_a = read_models_status(&cb, &org_id_a).await;
    assert!(
        is_denied(a_models_on_b) && is_denied(b_models_on_a),
        "VERIFIED_LIVE FAILURE: model cross-tenant access not denied (A->B={a_models_on_b}, B->A={b_models_on_a})"
    );
    println!("negative control: cross-tenant model access denied in both directions");

    let a_chat_on_b = chat_access_status(&ca, &org_id_b).await;
    let b_chat_on_a = chat_access_status(&cb, &org_id_a).await;
    assert!(
        is_denied(a_chat_on_b) && is_denied(b_chat_on_a),
        "VERIFIED_LIVE FAILURE: chat cross-tenant access not denied (A->B={a_chat_on_b}, B->A={b_chat_on_a})"
    );
    println!("negative control: cross-tenant chat access denied in both directions");

    println!(
        "VERIFIED_LIVE cross-tenant isolation holds in both directions (models, workspaces, chats)"
    );
}

fn is_denied(status: u16) -> bool {
    // Authenticated denial only; 401 (unauthenticated) does not prove isolation.
    status == 403 || status == 404
}

/// Resolve an org ID by name for the caller's token; panic if not visible.
async fn org_id_for(client: &CoderClient, name: &str) -> String {
    let orgs = client
        .list_organizations()
        .await
        .unwrap_or_else(|e| panic!("list orgs for {name}: {e}"));
    orgs.iter()
        .find(|o| o.name == name)
        .map(|o| o.id.clone())
        .unwrap_or_else(|| panic!("org {name} not visible to the calling identity"))
}

/// The outcome of a caller's attempt to read a workspace by name.
#[derive(Debug, Clone, PartialEq, Eq)]
enum WorkspaceAccess {
    /// The caller successfully listed and saw the workspace (200 + present).
    Visible,
    /// A valid response established the workspace is not visible: an empty 200
    /// (correct isolation) or an explicit authorization denial (403/404).
    NotVisible,
}

/// Pure decision function mapping an HTTP status and workspace-presence to an
/// isolation outcome. Only valid responses establish isolation: an explicit
/// authenticated denial (403/404) or a valid 200. Any other status (5xx, 401)
/// or a zero status (network failure) is an error and must NOT be treated as
/// proof of invisibility.
fn classify_workspace_access(status: u16, present: bool) -> Result<WorkspaceAccess, String> {
    if status == 403 || status == 404 {
        return Ok(WorkspaceAccess::NotVisible);
    }
    if status != 200 {
        return Err(format!("list workspaces returned HTTP {status}"));
    }
    if present {
        Ok(WorkspaceAccess::Visible)
    } else {
        // A valid empty 200 (only the summary row) is correct isolation.
        Ok(WorkspaceAccess::NotVisible)
    }
}

/// Classify a valid 200 `WorkspacesResponse` body for workspace isolation.
///
/// The body MUST carry a `workspaces` array (Coder returns
/// `{"workspaces": [...], "count": n}`, possibly empty). A malformed body with
/// no `workspaces` field or a non-array value (e.g. `{}` or
/// `{"workspaces": null}`) is an error and must NOT be treated as "not
/// visible" — otherwise a garbled response could satisfy the negative
/// isolation check.
fn classify_workspace_body(body: &Value, ws_name: &str) -> Result<WorkspaceAccess, String> {
    let workspaces = body
        .get("workspaces")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            "workspace response is malformed: missing a `workspaces` array".to_string()
        })?;
    let present = workspaces
        .iter()
        .any(|w| w.get("name").and_then(Value::as_str) == Some(ws_name));
    if present {
        Ok(WorkspaceAccess::Visible)
    } else {
        Ok(WorkspaceAccess::NotVisible)
    }
}

/// Probe whether the caller can list the workspace named `ws_name`.
///
/// Only valid responses establish isolation. A request failure (timeout,
/// network error), an unexpected HTTP status (5xx), an unauthenticated 401, or
/// a malformed body is returned as `Err` and must NOT be treated as proof of
/// invisibility — that could flag a secure deployment as insecure or let a
/// broken credential pass.
async fn workspace_access(client: &CoderClient, ws_name: &str) -> Result<WorkspaceAccess, String> {
    let resp = http_client()
        .get(format!(
            "{}/api/v2/workspaces?q=name:{}",
            client.base_url(),
            ws_name
        ))
        .header("Authorization", format!("Bearer {}", client.token()))
        .send()
        .await
        .map_err(|e| format!("list workspaces {ws_name} request failed: {e}"))?;
    let status = resp.status().as_u16();
    if status == 403 || status == 404 {
        return Ok(WorkspaceAccess::NotVisible);
    }
    if status != 200 {
        return Err(format!("list workspaces {ws_name} returned HTTP {status}"));
    }
    let body: Value = resp
        .json()
        .await
        .map_err(|e| format!("list workspaces {ws_name} body invalid: {e}"))?;
    classify_workspace_body(&body, ws_name)
}

async fn read_models_expect(client: &CoderClient, org_id: &str, label: &str) -> usize {
    let resp = http_client()
        .get(format!(
            "{}/api/v2/organizations/{}/chats/models",
            client.base_url(),
            org_id
        ))
        .header("Authorization", format!("Bearer {}", client.token()))
        .send()
        .await
        .unwrap_or_else(|e| panic!("{label}: request failed: {e}"));
    assert!(
        resp.status().is_success(),
        "{label}: expected 200, got {}",
        resp.status()
    );
    let body: Value = resp.json().await.unwrap_or(Value::Null);
    body.get("providers")
        .and_then(Value::as_array)
        .map(|a| a.len())
        .unwrap_or(0)
}

/// Status code returned when the caller reads chat models in `org_id`.
/// Used for cross-tenant model negative checks.
async fn read_models_status(client: &CoderClient, org_id: &str) -> u16 {
    http_client()
        .get(format!(
            "{}/api/v2/organizations/{}/chats/models",
            client.base_url(),
            org_id
        ))
        .header("Authorization", format!("Bearer {}", client.token()))
        .send()
        .await
        .map(|r| r.status().as_u16())
        .unwrap_or(0)
}

/// Create a chat in the caller's own org; must succeed (2xx).
async fn chat_access_ok(client: &CoderClient, org_id: &str) -> bool {
    let resp = http_client()
        .post(format!("{}/api/v2/chats", client.base_url()))
        .header("Authorization", format!("Bearer {}", client.token()))
        .json(&serde_json::json!({
            "organization_id": org_id,
            "content": [{"type": "text", "text": "probe"}]
        }))
        .send()
        .await;
    match resp {
        Ok(r) => r.status().is_success(),
        Err(_) => false,
    }
}

async fn chat_access_status(client: &CoderClient, org_id: &str) -> u16 {
    http_client()
        .post(format!("{}/api/v2/chats", client.base_url()))
        .header("Authorization", format!("Bearer {}", client.token()))
        .json(&serde_json::json!({
            "organization_id": org_id,
            "content": [{"type": "text", "text": "probe"}]
        }))
        .send()
        .await
        .map(|r| r.status().as_u16())
        .unwrap_or(0)
}

// ── Cleanup (prefix `cleanup_`, explicit, org-scoped) ──────────────────────
// Validates deployment URL and org before deleting, deletes children before
// parents, org-scopes every delete, keeps a provisioner running so the
// Terraform deletion job can execute, and retains entries whose deletion failed.

#[tokio::test]
#[ignore = "deletes resources recorded in the ledger; requires OPENFLOWS_CODER_MUTATE=1"]
async fn cleanup_created_resources() {
    require_mutate();
    let client = require_live_client();
    let deployment = coder_url().expect("CODER_URL");
    let ledger = with_ledger_lock(load_ledger_locked);

    // Only consider entries belonging to THIS deployment and org prefix.
    let candidates: Vec<LedgerEntry> = ledger
        .entries
        .iter()
        .filter(|e| e.deployment_url == deployment && e.org.starts_with(&org_prefix()))
        .cloned()
        .collect();

    // Workspace and template deletion each need a provisioner daemon to run the
    // Terraform deletion job. Spin one up per org that owns any such resource.
    let mut daemons: Vec<tokio::process::Child> = Vec::new();
    let orgs_needing_provisioner: std::collections::BTreeSet<String> = candidates
        .iter()
        .filter(|e| matches!(e.kind.as_str(), "workspace" | "template"))
        .map(|e| e.org.clone())
        .collect();
    for org in &orgs_needing_provisioner {
        // Resolve the org id for the daemon's --org flag from the ledger org
        // entry; fall back to the org name.
        let org_id = candidates
            .iter()
            .find(|e| e.kind == "org" && e.org == *org)
            .map(|e| e.resource_id.clone())
            .filter(|id| !id.is_empty())
            .unwrap_or_else(|| org.clone());
        if read_provisioner_secret(&org_id).is_some() {
            daemons.push(start_provisioner_daemon(&org_id));
        } else {
            println!(
                "cleanup WARN: no stored provisioner daemon secret for org {org}; \
                 deletion jobs for it may remain queued"
            );
        }
    }

    // Child-before-parent deletion order. If a child (workspace/template)
    // deletion fails for an org, its parent dependencies (template, user,
    // provisioner key, org) are recovery dependencies for the pending deletion
    // job and MUST be preserved so a retry can finish. We track failed orgs and
    // skip every later dependency for them.
    let mut failed_orgs: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    let order: &[&str] = &["workspace", "template", "user", "provisioner_key", "org"];
    for kind in order {
        for entry in candidates.iter().filter(|e| e.kind == *kind) {
            // Preserve all remaining dependencies once an org's deletion failed.
            if failed_orgs.contains(&entry.org) {
                println!(
                    "cleanup SKIP {} {} (org {}): a dependency failed earlier; preserving for retry",
                    kind, entry.id, entry.org
                );
                continue;
            }
            let org_id = candidates
                .iter()
                .find(|e| e.kind == "org" && e.org == entry.org)
                .map(|e| e.resource_id.clone())
                .unwrap_or_default();
            let ok = delete_resource(&client, kind, &entry.id, &entry.org, &org_id).await;
            ledger_delete_result(kind, &entry.id, &entry.resource_id, &entry.org, ok);
            if ok {
                println!("cleanup {} {} (org {})", kind, entry.id, entry.org);
            } else {
                println!(
                    "cleanup FAILED {} {} (org {}); retained for retry and dependencies preserved",
                    kind, entry.id, entry.org
                );
                failed_orgs.insert(entry.org.clone());
            }
        }
    }

    for mut d in daemons {
        stop_provisioner_daemon(&mut d).await;
    }

    // Cleanup is only complete when every candidate is gone. A failed deletion
    // (or a dependency preserved because of one) must fail the command so the
    // caller knows resources remain.
    if !failed_orgs.is_empty() {
        panic!(
            "cleanup INCOMPLETE: deletion failed and dependencies were preserved for org(s) {:?}; \
             re-run --cleanup after the pending deletion job completes.",
            failed_orgs
        );
    }
}

async fn delete_resource(
    client: &CoderClient,
    kind: &str,
    id: &str,
    org: &str,
    org_id: &str,
) -> bool {
    assert_not_default_org(org);
    // Every deletion runs under a wall-clock deadline via `coder_cli_timeout`
    // (which sets kill_on_drop and kills/reaps the child on timeout), so a
    // stalled deletion job or an unreachable provisioner cannot hang cleanup.
    // On timeout the call returns an error, the deletion is marked failed, and
    // the org's dependencies are preserved for retry.
    let timeout = std::time::Duration::from_secs(120);
    match kind {
        "provisioner_key" => match delete_provisioner_key_api(client, org_id, id).await {
            Ok(()) => true,
            Err(e) => {
                println!(
                    "cleanup provisioner_key {} failed: {}",
                    id,
                    redact_string(&e)
                );
                false
            }
        },
        "workspace" => coder_cli_timeout(&["delete", "--yes", id], org, timeout)
            .await
            .is_ok(),
        "template" => coder_cli_timeout(&["templates", "delete", "--yes", id], org, timeout)
            .await
            .is_ok(),
        "user" => coder_cli_timeout(&["users", "delete", "--yes", id], "", timeout)
            .await
            .is_ok(),
        "org" => coder_cli_timeout(&["organizations", "delete", "--yes", id], "", timeout)
            .await
            .is_ok(),
        _ => false,
    }
}

// ── Fixture ────────────────────────────────────────────────────────────────

/// A valid, minimal, secret-free Terraform template for publication checks.
const VALID_MINIMAL_MAIN_TF: &str = r#"terraform {
  required_providers {
    coder = {
      source  = "coder/coder"
      version = "~> 2.18.0"
    }
  }
}

data "coder_workspace" "me" {}

resource "coder_agent" "main" {
  os   = "linux"
  arch = "amd64"
}
"#;

// ── Offline regression tests (never touch a deployment) ────────────────────
// These are plain `#[test]`s (not `#[ignore]`d) so `cargo test -p coder-client
// --test compatibility` exercises the parsing/validation helpers without a
// live Coder. Compilation alone has repeatedly missed these failures, so the
// helpers must be pinned by executable tests.

#[cfg(test)]
mod offline {
    use super::*;

    #[test]
    fn extract_daemon_key_structured_json_response() {
        // The canonical POST /provisionerkeys response: {"key": "<43 chars>"}.
        let secret = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFG";
        assert_eq!(secret.len(), 43);
        let out = format!("{{\"key\": \"{secret}\"}}");
        assert_eq!(extract_daemon_key(&out).as_deref(), Some(secret));
    }

    #[test]
    fn extract_daemon_key_rejects_wrong_length() {
        let short = "abcdefghijklmnopqrstuvwxyzABC";
        assert_eq!(
            extract_daemon_key(&format!("{{\"key\": \"{short}\"}}")),
            None
        );
        let long = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123";
        assert_eq!(
            extract_daemon_key(&format!("{{\"key\": \"{long}\"}}")),
            None
        );
    }

    #[test]
    fn extract_daemon_key_rejects_coder_prefixed_and_non_alnum() {
        // A `coder_`-prefixed string is NOT the pinned format and must be
        // rejected, so a stale regex cannot silently accept the wrong secret.
        assert_eq!(
            extract_daemon_key("coder_abcdefghijklmnopqrstuvwxyz1234567"),
            None
        );
        let secret = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFG";
        let bad = format!("{secret}-");
        assert_eq!(extract_daemon_key(&bad), None);
    }

    #[test]
    fn extract_daemon_key_plaintext_standalone_line() {
        // If a real CLI printed the raw secret on its own line, we still parse
        // it (the pinned implementation does not print a coder_ prefix).
        let secret = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFG";
        assert_eq!(secret.len(), 43);
        let out = format!(
            "Provisioner key created\n{secret}\nSave this key now; it will not be shown again.\n"
        );
        assert_eq!(extract_daemon_key(&out).as_deref(), Some(secret));
    }

    #[test]
    fn extract_daemon_key_empty_and_noise() {
        assert_eq!(extract_daemon_key(""), None);
        assert_eq!(
            extract_daemon_key("Provisioner key created\n\nSave it now.\n"),
            None
        );
    }

    #[test]
    fn is_provisioner_secret_validates_shape() {
        let valid = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFG";
        assert_eq!(valid.len(), 43);
        assert!(is_provisioner_secret(valid));
        assert!(!is_provisioner_secret(""));
        assert!(!is_provisioner_secret("abcdefghijklmnopqrstuvwxyzABC"));
        assert!(!is_provisioner_secret(
            "0123456789abcdefghijklmnopqrstuvwxyzABCDEFG!"
        ));
    }

    #[test]
    fn validate_workspace_identity_matches_exact_fields() {
        // Pinned API shape: a successful start reports latest_build.status ==
        // "running" (WorkspaceStatus) and latest_build.job.status == "succeeded"
        // (ProvisionerJobStatus).
        let ws = serde_json::json!({
            "id": "ws-111",
            "name": "ofci-check-a",
            "owner_id": "u-1",
            "owner_name": "ofci-sa-a",
            "organization_id": "org-1",
            "template_id": "tpl-1",
            "template_name": "ofci-nexus-a",
            "latest_build": {
                "status": "running",
                "template_version_id": "tv-1",
                "template_version_name": "ofci-wp00-deadbeef",
                "job": {"status": "succeeded"}
            }
        });
        let id = validate_workspace_identity(
            &ws,
            "org-1",
            "ofci-sa-a",
            "ofci-nexus-a",
            "ofci-wp00-deadbeef",
            "running",
        )
        .expect("identity should match");
        assert_eq!(id, "ws-111");
    }

    #[test]
    fn validate_workspace_identity_rejects_wrong_org() {
        let ws = serde_json::json!({
            "id": "ws-1",
            "owner_name": "ofci-sa-a",
            "organization_id": "org-WRONG",
            "template_name": "ofci-nexus-a",
            "latest_build": {
                "status": "running",
                "template_version_name": "ofci-wp00-x",
                "job": {"status": "succeeded"}
            }
        });
        assert!(validate_workspace_identity(
            &ws,
            "org-1",
            "ofci-sa-a",
            "ofci-nexus-a",
            "ofci-wp00-x",
            "running"
        )
        .is_err());
    }

    #[test]
    fn validate_workspace_identity_rejects_wrong_owner() {
        let ws = serde_json::json!({
            "id": "ws-1",
            "owner_name": "somebody-else",
            "organization_id": "org-1",
            "template_name": "ofci-nexus-a",
            "latest_build": {
                "status": "running",
                "template_version_name": "ofci-wp00-x",
                "job": {"status": "succeeded"}
            }
        });
        assert!(validate_workspace_identity(
            &ws,
            "org-1",
            "ofci-sa-a",
            "ofci-nexus-a",
            "ofci-wp00-x",
            "running"
        )
        .is_err());
    }

    #[test]
    fn validate_workspace_identity_rejects_wrong_version() {
        let ws = serde_json::json!({
            "id": "ws-1",
            "owner_name": "ofci-sa-a",
            "organization_id": "org-1",
            "template_name": "ofci-nexus-a",
            "latest_build": {
                "status": "running",
                "template_version_name": "ofci-wp00-OLD",
                "job": {"status": "succeeded"}
            }
        });
        assert!(validate_workspace_identity(
            &ws,
            "org-1",
            "ofci-sa-a",
            "ofci-nexus-a",
            "ofci-wp00-x",
            "running"
        )
        .is_err());
    }

    #[test]
    fn validate_workspace_identity_rejects_status_succeeded() {
        // `latest_build.status == "succeeded"` never occurs for a start in the
        // pinned API; only `latest_build.job.status` may be "succeeded". The
        // validator must reject the wrong status so a stale expectation fails.
        let ws = serde_json::json!({
            "id": "ws-1",
            "owner_name": "ofci-sa-a",
            "organization_id": "org-1",
            "template_name": "ofci-nexus-a",
            "latest_build": {
                "status": "succeeded",
                "template_version_name": "ofci-wp00-x",
                "job": {"status": "succeeded"}
            }
        });
        assert!(validate_workspace_identity(
            &ws,
            "org-1",
            "ofci-sa-a",
            "ofci-nexus-a",
            "ofci-wp00-x",
            "running"
        )
        .is_err());
    }

    #[test]
    fn validate_workspace_identity_rejects_unfinished_job() {
        // A job still pending/running must not be accepted as a completed
        // workspace build, even though the workspace status may be "starting".
        let ws = serde_json::json!({
            "id": "ws-1",
            "owner_name": "ofci-sa-a",
            "organization_id": "org-1",
            "template_name": "ofci-nexus-a",
            "latest_build": {
                "status": "starting",
                "template_version_name": "ofci-wp00-x",
                "job": {"status": "running"}
            }
        });
        assert!(validate_workspace_identity(
            &ws,
            "org-1",
            "ofci-sa-a",
            "ofci-nexus-a",
            "ofci-wp00-x",
            "running"
        )
        .is_err());
    }

    #[test]
    fn build_wait_success_accepts_running_and_job_succeeded() {
        // A successful start is signaled by latest_build.status == "running"
        // and/or latest_build.job.status == "succeeded".
        let running = serde_json::json!({
            "id": "ws-1",
            "latest_build": {"status": "running", "job": {"status": "running"}}
        });
        assert!(build_wait_is_success(&running));
        let job_done = serde_json::json!({
            "id": "ws-2",
            "latest_build": {"status": "starting", "job": {"status": "succeeded"}}
        });
        assert!(build_wait_is_success(&job_done));
        let pending = serde_json::json!({
            "id": "ws-3",
            "latest_build": {"status": "starting", "job": {"status": "pending"}}
        });
        assert!(!build_wait_is_success(&pending));
    }

    /// Pure mirror of the terminal-success logic in
    /// `wait_for_workspace_build_succeeded`.
    fn build_wait_is_success(ws: &Value) -> bool {
        let ws_status = ws
            .get("latest_build")
            .and_then(|b| b.get("status"))
            .and_then(Value::as_str)
            .unwrap_or("");
        let job_status = ws
            .get("latest_build")
            .and_then(|b| b.get("job"))
            .and_then(|j| j.get("status"))
            .and_then(Value::as_str)
            .unwrap_or("");
        job_status == "succeeded" || ws_status == "running"
    }

    #[test]
    fn classify_workspace_access_valid_outcomes() {
        // A valid 200 with the workspace present is Visible.
        assert_eq!(
            classify_workspace_access(200, true),
            Ok(WorkspaceAccess::Visible)
        );
        // A valid 200 with the workspace absent is correct isolation.
        assert_eq!(
            classify_workspace_access(200, false),
            Ok(WorkspaceAccess::NotVisible)
        );
        // Explicit authenticated denials are valid isolation.
        assert_eq!(
            classify_workspace_access(403, false),
            Ok(WorkspaceAccess::NotVisible)
        );
        assert_eq!(
            classify_workspace_access(404, false),
            Ok(WorkspaceAccess::NotVisible)
        );
    }

    #[test]
    fn classify_workspace_access_errors_never_prove_invisibility() {
        // A request failure / unexpected status must NOT be treated as proof
        // of isolation. Otherwise a broken credential or hung server passes.
        assert!(classify_workspace_access(500, false).is_err());
        assert!(classify_workspace_access(401, false).is_err());
        assert!(classify_workspace_access(503, false).is_err());
        // 0 represents a network/timeout failure (request never completed).
        assert!(classify_workspace_access(0, false).is_err());
    }

    #[test]
    fn find_workspace_in_response_empty_200_is_not_found() {
        // An empty 200 (only the technical summary row) is a correct, valid
        // response and must be treated as "workspace not visible", never a panic.
        let body = serde_json::json!({ "workspaces": [], "count": 0 });
        assert!(find_workspace_in_response(&body, "ofci-check-a").is_none());
    }

    #[test]
    fn find_workspace_in_response_matches_exact_name() {
        let body = serde_json::json!({
            "workspaces": [
                {"name": "ofci-check-a", "id": "ws-a"},
                {"name": "ofci-check-b", "id": "ws-b"}
            ]
        });
        assert_eq!(
            find_workspace_in_response(&body, "ofci-check-b")
                .and_then(|w| w.get("id").and_then(Value::as_str).map(String::from))
                .as_deref(),
            Some("ws-b")
        );
    }

    #[test]
    fn ledger_identity_is_distinct_across_orgs() {
        // The same kind+human name in two orgs must NOT collide.
        let a = ledger_identity("https://coder", "org-a", "template", "tpl-a");
        let b = ledger_identity("https://coder", "org-b", "template", "tpl-a");
        assert_ne!(a, b);
        // Same org, different resource IDs also distinct.
        let c = ledger_identity("https://coder", "org-a", "template", "tpl-b");
        assert_ne!(a, c);
        // Different deployment must not collide.
        let d = ledger_identity("https://other", "org-a", "template", "tpl-a");
        assert_ne!(a, d);
    }

    #[test]
    fn ledger_identity_is_stable_and_deterministic() {
        let a1 = ledger_identity("https://coder", "org-a", "workspace", "ws-1");
        let a2 = ledger_identity("https://coder", "org-a", "workspace", "ws-1");
        assert_eq!(a1, a2);
    }

    #[test]
    fn provisioner_daemon_status_classification() {
        let key = "ofci-key-a";
        assert!(daemon_matches_online(
            &serde_json::json!([{"key_name": key, "status": "idle", "name": "d1"}]),
            key
        ));
        assert!(daemon_matches_online(
            &serde_json::json!([{"key_name": key, "status": "busy", "name": "d1"}]),
            key
        ));
        assert!(!daemon_matches_online(
            &serde_json::json!([{"key_name": key, "status": "offline", "name": "d1"}]),
            key
        ));
        assert!(!daemon_matches_online(
            &serde_json::json!([{"key_name": "ofci-key-other", "status": "idle", "name": "d1"}]),
            key
        ));
        assert!(!daemon_matches_online(&serde_json::json!([]), key));
    }

    /// Pure mirror of the identity+status logic in `provisioner_daemons_ready`.
    fn daemon_matches_online(daemons: &Value, key_name: &str) -> bool {
        daemons
            .as_array()
            .map(|arr| {
                arr.iter().any(|d| {
                    d.get("key_name").and_then(Value::as_str) == Some(key_name)
                        && matches!(
                            d.get("status").and_then(Value::as_str),
                            Some("idle") | Some("busy")
                        )
                })
            })
            .unwrap_or(false)
    }
}
