-- WP-01 migration 0001: Identity and membership domain.
--
-- Covers the user, identity, organization, membership, invitation, session,
-- refresh-history, auth-transaction, and CLI-login-request tables from
-- docs/implementation/centralized-deployment/01-user-management.md.
--
-- UUID primary keys are server-generated by the application unless stated
-- otherwise. Every row carries created_at/updated_at where appropriate.
--
-- The organization <-> owner deferred FK is applied in a later migration
-- because it depends on the memberships table defined here and must be
-- deferrable so an organization and its creator's membership can be created in
-- one transaction.

-- Human users. Independent of any organization; a user may belong to many.
CREATE TABLE users (
    id            UUID PRIMARY KEY,
    display_name  TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'suspended', 'deleted')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- External provider identities. v1 uses GitHub's immutable numeric user id as
-- the provider subject. Never merge by display name, login, or email.
CREATE TABLE identities (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id),
    provider        TEXT NOT NULL,
    subject         TEXT NOT NULL,
    login_snapshot  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, subject)
);

-- Organizations. One Openflows organization maps to exactly one Coder
-- organization. Ownership is a separate field, not a membership role.
CREATE TABLE organizations (
    id                    UUID PRIMARY KEY,
    slug                  TEXT NOT NULL,
    display_name          TEXT NOT NULL,
    owner_user_id         UUID NOT NULL REFERENCES users(id),
    status                TEXT NOT NULL DEFAULT 'provisioning'
                          CHECK (status IN ('provisioning', 'ready', 'suspended', 'deleting', 'deleted')),
    coder_organization_id TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (slug),
    UNIQUE (coder_organization_id)
);

-- Memberships. Composite PK (organization_id, user_id). role is a product
-- membership role; ownership is tracked separately on organizations.
CREATE TABLE memberships (
    organization_id UUID NOT NULL REFERENCES organizations(id),
    user_id         UUID NOT NULL REFERENCES users(id),
    role            TEXT NOT NULL CHECK (role IN ('admin', 'developer', 'viewer')),
    status          TEXT NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'suspended', 'removed')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (organization_id, user_id)
);

-- Invitations. token_hash is unique; at most one live invitation per
-- organization/subject (enforced by the partial unique index below).
CREATE TABLE invitations (
    id                     UUID PRIMARY KEY,
    organization_id        UUID NOT NULL REFERENCES organizations(id),
    invitee_github_user_id BIGINT NOT NULL,
    role                   TEXT NOT NULL CHECK (role IN ('admin', 'developer', 'viewer')),
    token_hash             TEXT NOT NULL,
    invited_by             UUID REFERENCES users(id),
    expires_at             TIMESTAMPTZ NOT NULL,
    accepted_at            TIMESTAMPTZ,
    revoked_at             TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (token_hash)
);

-- A live invitation is one that has not been accepted or revoked. The partial
-- unique index enforces "one outstanding invitation per org/subject" at the
-- database level. Expiry is enforced in the service layer (an expired
-- invitation is revoked before a replacement is issued), because a predicate
-- using now() would not be IMMUTABLE and cannot be indexed.
CREATE UNIQUE INDEX one_live_invitation_per_org_subject
    ON invitations (organization_id, invitee_github_user_id)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;

-- Sessions. kind is browser or cli. Hash high-entropy access/refresh tokens
-- with SHA-256; unique hashes.
CREATE TABLE sessions (
    id                 UUID PRIMARY KEY,
    user_id            UUID NOT NULL REFERENCES users(id),
    kind               TEXT NOT NULL CHECK (kind IN ('browser', 'cli')),
    access_hash        TEXT NOT NULL,
    access_expires_at  TIMESTAMPTZ NOT NULL,
    refresh_hash       TEXT NOT NULL,
    refresh_expires_at TIMESTAMPTZ NOT NULL,
    family_id          UUID NOT NULL,
    revoked_at         TIMESTAMPTZ,
    last_used_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (access_hash),
    UNIQUE (refresh_hash)
);

-- Refresh history detects refresh-token reuse (a rotated, already-consumed
-- refresh credential revokes its session family).
CREATE TABLE refresh_history (
    refresh_hash TEXT PRIMARY KEY,
    family_id    UUID NOT NULL,
    consumed_at  TIMESTAMPTZ NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL
);

-- Auth transactions for browser/device login and GitHub-connect flows.
CREATE TABLE auth_transactions (
    id              UUID PRIMARY KEY,
    purpose         TEXT NOT NULL CHECK (purpose IN ('login', 'github_connect')),
    state_hash      TEXT NOT NULL,
    user_id         UUID REFERENCES users(id),
    organization_id UUID REFERENCES organizations(id),
    pkce_verifier   BYTEA,
    expires_at      TIMESTAMPTZ NOT NULL,
    consumed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (state_hash)
);

-- CLI device-approval requests.
CREATE TABLE cli_login_requests (
    id                UUID PRIMARY KEY,
    device_secret_hash TEXT NOT NULL,
    user_code_hash     TEXT NOT NULL,
    status             TEXT NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending', 'approved', 'consumed', 'expired')),
    approved_user_id   UUID REFERENCES users(id),
    expires_at         TIMESTAMPTZ NOT NULL,
    last_poll_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (device_secret_hash),
    UNIQUE (user_code_hash)
);
